### ISSUE TITLE
Cant get balance of wallet v1 r3

### ISSUE THREAD

**Issue by SergeyLepesev** [continuation-team/TonSdk.NET#38]
Hello!
Cannot get balance info from wallet v1 r3. 

Step to reproduce 
1. `TonClient.GetBalance()` of any v1 r3 wallet. for example `Ef_BvG8IeNYQFsOQ8Z5WqhcFLAcjZP_rvx-5_y32IyIYkMh2`
2. Check return value. Coins will be zero.  

![image](https://github.com/continuation-team/TonSdk.NET/assets/30021495/3f242b42-5e88-49a0-ae8d-b3c82f56d099)
![image](https://github.com/continuation-team/TonSdk.NET/assets/30021495/a0d7776f-91f5-4b28-ac84-ddf3ca8131bb)

**Comment by SergeyLepesev** [comment]
We use own toncenter. Method get balance return right value
![image](https://github.com/continuation-team/TonSdk.NET/assets/30021495/7f67cc45-ec65-4dc0-9e5d-1e6c7a456205)

**Comment by SergeyLepesev** [comment]
As a possible solution, I suggest adding a `GetWalletInformation` method in the `Wallet` class, which will request api data from `toncenter/getWalletInformation`

**Comment by VitaliiBakatov** [comment]
https://github.com/continuation-team/TonSdk.NET/blob/3ded5733ae115b7166b75a5047f282e83f7b3238/TonSdk.Client/src/HttpApi/HttpsApi.cs#L56C35-L56C35

The problem is that address is requested in workchain 0.

A new class AddressStringifyOptions is created, which defaults to 0 in workchain
![изображение](https://github.com/continuation-team/TonSdk.NET/assets/61192246/abb89f7f-eb74-4c14-8d67-b523bc8b7dc0)

You need to check params of address that is being passed to method

**Comment by purpleguy99** [comment]
We will add the update in these week. Stay tuned.

**Comment by purpleguy99** [comment]
Issue was fixed. Please check the PR https://github.com/continuation-team/TonSdk.NET/pull/44. Updates will displayed in Nuget in one day.
